### ISSUE TITLE
Fine-grained output

### ISSUE THREAD

**Issue by antonio-mastropaolo** [SpoonLabs/gumtree-spoon-ast-diff#238]
Hello everybody, I was wondering if there exists a way to map/display editScripts operations in a fine-grained way.
With that I mean something like the following:
   ```
        Move BinaryOperator from Test:5 to Test:5
	(VAR_4 < VAR_2)

       Insert Block at Test:5
	{
	    if ()  else {
	        VAR_4 = VAR_3;
	    }
	}

       Insert If at Test:6
	if ()  else {
	    VAR_4 = VAR_3;
	}
```
to

Move BinaryOperator from BinaryOperator to CtBinaryOperatorImpl
Insert Block at If
Insert If at Block

I'm asking this because I saw some researchers have already done this, but since I'm new to gumtree, I thought to ask before doing anything crazy.

**Comment by algomaster99** [comment]
@antonio-mastropaolo Hey! Sorry for replying late. But I hope my answer will still help you or someone else if they come across this issue.

GumTree is supposed to return `fine-grained` AST differences. For example, if a line-based diff shows the following:
```diff
- if (x > 0) { }
+ if (x < 0) { }
```
GumTree algorithm will _precisely_ tell you that the binary operator in the AST has been updated at a particular position.

What you have reported are just string representations of the operations, but they encapture the precise AST differences between the nodes. I am quite sure they would be correct although I am not guaranteeing since I have not seen the left and right revisions. If you want more "precise string representations", I would suggest you extending the [`Operation`](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/diff/operations/Operation.java#L34) class and override the `toString` method.

I have noted that you are using `getAllOperations` from the diff you posted because the third operation is encompassed in the second operation. If you do not desire that, you can use `getRootOperations`. Please note that it is perfectly fine to use the former API as well, if that is what your experiment desires.
